# Generated by Django 6.0.7 on 2026-07-15 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('billing', 'Billing'), ('bug', 'Bug'), ('feature_request', 'Feature Request'), ('technical', 'Technical'), ('account', 'Account'), ('general', 'General')], db_index=True, max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, max_length=10)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('suggested_reply', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('processing_time', models.FloatField(blank=True, help_text='Seconds', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tickets_tic_user_id_34dfee_idx'), models.Index(fields=['user', 'status'], name='tickets_tic_user_id_ee01b8_idx')],
            },
        ),
    ]
